# Generated by Django 2.1.5 on 2020-05-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200505_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='cost',
            new_name='cost_large',
        ),
        migrations.AddField(
            model_name='menu',
            name='cost_small',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='size',
            field=models.CharField(choices=[('large', 'LARGE'), ('small', 'SMALL'), ('standart', 'STANDART')], default='standart', max_length=10),
        ),
    ]
