# Generated by Django 2.1.5 on 2020-05-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200510_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='size',
            field=models.CharField(choices=[('small/large', 'SMALL/LARGE'), ('standart', 'STANDART')], default='standart', max_length=15),
        ),
    ]
