# Generated by Django 2.1.5 on 2020-05-10 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_auto_20200510_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('marked', 'MARKED'), ('ordered', 'ORDERED'), ('done', 'DONE')], max_length=15)),
                ('date', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('size', models.CharField(max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='orders.menu')),
                ('topping', models.ManyToManyField(blank=True, related_name='toppingsONorder', to='orders.toppings')),
                ('user', models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
